name = "agicook-tally"
main = "src/index.js"
compatibility_date = "2026-08-29"

# database_id is filled in by `wrangler d1 create agicook-quiz`
[[d1_databases]]
binding = "DB"
database_name = "agicook-quiz"
database_id = "d9ec5a4e-bad5-45b5-9798-a5f4a725febf"
